In [1]:
# log transformation: > when the data is right skewed
import pandas as pd
import numpy as np

x = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
y = np.log1p(x)
print(y)

0    0.693147
1    1.098612
2    1.386294
3    1.609438
4    1.791759
5    1.945910
6    2.079442
7    2.197225
8    2.302585
9    2.397895
dtype: float64


### determine skewness using mean and median:
``` 
  mean = df["col"].mean()
  median = df["col"].median()
```

- Right-skewed (positive skew) → Mean > Median
- Left-skewed (negative skew) → Mean < Median
- Symmetric → Mean ≈ Median

### using skewness to determine the type of skewness:
```
df["col"].skew()
```
  - skewness > 0 → right-skewed
  - skewness < 0 → left-skewed
  - skewness ≈ 0 → symmetric

In [2]:
# square root transformation: > when the data is moderately right skewed
y = np.sqrt(x)
print(y)

0    1.000000
1    1.414214
2    1.732051
3    2.000000
4    2.236068
5    2.449490
6    2.645751
7    2.828427
8    3.000000
9    3.162278
dtype: float64


In [9]:
# power transformation: > when the data is left skewed
# > used when distribution is unknown
# > yeo-johnson: can be applied to both positive and negative data
# > box-cox: can only be applied to positive data

from sklearn.preprocessing import PowerTransformer

pt = PowerTransformer(method='yeo-johnson')
x_reshaped = pt.fit_transform(x.values.reshape(-1, 1))
print(x_reshaped)

[[-1.67954974]
 [-1.23932568]
 [-0.83773822]
 [-0.46263446]
 [-0.10736913]
 [ 0.23220439]
 [ 0.55889855]
 [ 0.8747344 ]
 [ 1.18122753]
 [ 1.47955236]]


In [11]:
# Normalization: > when the data is on different scales
# Min-max normalization performs a linear transformation on the original data.

from sklearn.preprocessing import MinMaxScaler
import numpy as np

data = np.array([[200], [300], [400], [500], [600]])

# initializing the scaler
scaler = MinMaxScaler(feature_range=(0, 1))

# fitting and transforming the data
normalized_data = scaler.fit_transform(data)
print(f"original data:\n{data}\n")
print(f"normalized data:\n{normalized_data}\n")


original data:
[[200]
 [300]
 [400]
 [500]
 [600]]

normalized data:
[[0.  ]
 [0.25]
 [0.5 ]
 [0.75]
 [1.  ]]



In [12]:
# z-score normalization: 
from sklearn.preprocessing import StandardScaler

data = np.array([[200], [300], [400], [500], [600]])

scaler = StandardScaler()

normalized_data = scaler.fit_transform(data)
print(f"original data:\n{data}\n")
print(f"normalized data:\n{normalized_data}\n")

original data:
[[200]
 [300]
 [400]
 [500]
 [600]]

normalized data:
[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]



In [13]:
# decimal scaling normalization

data = np.array([[200], [300], [400], [500], [600]])
max_abs_value = np.max(np.abs(data))
j = len(str(int(max_abs_value)))
scaled_data = data / (10 ** j)
print(f"original data:\n{data}\n")
print(f"normalized data:\n{scaled_data}\n")

original data:
[[200]
 [300]
 [400]
 [500]
 [600]]

normalized data:
[[0.2]
 [0.3]
 [0.4]
 [0.5]
 [0.6]]



In [15]:
# label encoding: > when the data is categorical
# > assigns a unique integer to each category
# > works for ordinal data

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
categories = ['low', 'medium', 'high', 'medium', 'low']
encoded_labels = le.fit_transform(categories)
print(encoded_labels)

[1 2 0 2 1]


In [17]:
# one-hot encoding: > when the data is categorical
# > creates binary columns for each category
# > works for nominal data

import pandas as pd

df = pd.DataFrame({
    "Name": ["A", "B", "C", "D"],
    "City": ["Kathmandu", "Pokhara", "Kathmandu", "Biratnagar"]
})

print(df)

  Name        City
0    A   Kathmandu
1    B     Pokhara
2    C   Kathmandu
3    D  Biratnagar


In [18]:
encoded = pd.get_dummies(df["City"])
print(encoded)

   Biratnagar  Kathmandu  Pokhara
0       False       True    False
1       False      False     True
2       False       True    False
3        True      False    False


In [19]:
# adding to original dataframe
df_final = pd.concat([df, encoded], axis=1)
print(df_final)

  Name        City  Biratnagar  Kathmandu  Pokhara
0    A   Kathmandu       False       True    False
1    B     Pokhara       False      False     True
2    C   Kathmandu       False       True    False
3    D  Biratnagar        True      False    False


In [21]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder()

encoded = encoder.fit_transform(df[["City"]])

print(encoded)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 4 stored elements and shape (4, 3)>
  Coords	Values
  (0, 1)	1.0
  (1, 2)	1.0
  (2, 1)	1.0
  (3, 0)	1.0


In [25]:
# ordinal encoding: > when the data is ordinal
# Converts categories to integers, preserving order.
# When to use:
#  When categories have a meaningful order
#  Can be combined with scaling if needed

from sklearn.preprocessing import OrdinalEncoder

encoder = OrdinalEncoder(categories=[['low', 'medium', 'high']])
categories = [['low'], ['medium'], ['high'], ['medium'], ['low']]
encoded = encoder.fit_transform(categories)
print(encoded)

[[0.]
 [1.]
 [2.]
 [1.]
 [0.]]
